version: '3'
services:
  resume-name-remover-backend:
    container_name: resume-name-remover-backend
    build: ./backend
    ports:
      - "9000:9000"

  resume-name-remover-frontend:
    container_name: resume-name-remover-frontend
    build: ./frontend
    ports:
      - "9001:80"
    depends_on:
      - resume-name-remover-backend
    links:
      - resume-name-remover-backend
