Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude: 
    - 'spec/**/*'

Lint/MissingSuper:
  Exclude:
    - app/domain/name_retriever.rb
