source "https://rubygems.org"

gemspec

gem "rake", "~> 12.3"
gem "rspec", "~> 3.0"
gem "sinatra", "~> 2.2.0"
gem "rack"
gem "json"
gem "pdf-reader"
gem "prawn"
gem "webrick"

gem "webrat", :group => :test

gem "rubocop", :group => :development
